// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHSxAZOWhB1RONdZLEITiw1297auhXT0',
    appId: '1:551410384420:web:a9b56df81a2c002bdae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    authDomain: 'ezymember-1a58c.firebaseapp.com',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
    measurementId: 'G-9R1ZCK87FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnw5Ir3rbyAc81U_IZPSs-trozReFong',
    appId: '1:551410384420:android:d6eeae5871be623adae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuo0-omo8j0RpN00HtChjFlzTFDzgbifE',
    appId: '1:551410384420:ios:dca4ac0711125fdcdae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
    androidClientId: '551410384420-61lqmqeorptdvp5pr5ih01mt0sns6njc.apps.googleusercontent.com',
    iosClientId: '551410384420-99t7srl8sq7udcn9313f22hu1nns4pag.apps.googleusercontent.com',
    iosBundleId: 'com.ezysolutions.ezymember',
  );
}
