// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHSxAZOWhB1RONdZLEITiw1297auhXT0',
    appId: '1:551410384420:web:e0f43b771d90d8c2dae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    authDomain: 'ezymember-1a58c.firebaseapp.com',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
    measurementId: 'G-6C21ZDJTL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnw5Ir3rbyAc81U_IZPSs-trozReFong',
    appId: '1:551410384420:android:6e3e45fef7261d08dae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuo0-omo8j0RpN00HtChjFlzTFDzgbifE',
    appId: '1:551410384420:ios:174ac1b238fa7489dae2b1',
    messagingSenderId: '551410384420',
    projectId: 'ezymember-1a58c',
    storageBucket: 'ezymember-1a58c.firebasestorage.app',
    iosBundleId: 'com.example.ezyMemberV2',
  );
}
